# Generated by Django 4.0.4 on 2022-04-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugly_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeanswer',
            old_name='object',
            new_name='answer',
        ),
    ]
